baseURL = "https://mi-ki-ri.github.io/portal/"
languageCode = "jp"
title = "ミキリハッシャポータル"
canonifyurls = true
[params]
subTitle = "見切り発車Pが作った楽曲の情報サイト"
author = "mi.ki.ri.hassha.p@gmail.com"
dlPath = "mp3/"
[taxonomies]
tag = "tags"
