baseURL = "https://portal.mikiri.net/"
languageCode = "jp"
title = "ミキリハッシャポータル"
canonifyurls = true
[params]
subTitle = "見切り発車Pが作った楽曲の情報サイト"
author = "mi.ki.ri.hassha.p@gmail.com"
dlURL = "http://mymp3.mikiri.net/"
[taxonomies]
tag = "tags"
